# Generated by Django 4.2 on 2023-08-07 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=100)),
                ('employeeid', models.CharField(max_length=20)),
                ('assetid', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Others')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MainDashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('Catagory_name', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Asset_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=100)),
                ('Employee_id', models.CharField(max_length=100)),
                ('Group', models.CharField(max_length=100)),
                ('Sub_Group', models.CharField(max_length=100)),
                ('Contact_number', models.CharField(max_length=50)),
                ('Working_For_Client', models.BooleanField(default=True)),
                ('Client_Email_id', models.CharField(max_length=100)),
                ('Client_Laptop', models.CharField(max_length=100)),
                ('Client_Mouse', models.CharField(max_length=100)),
                ('Client_Headphones', models.CharField(max_length=100)),
                ('Client_Computer', models.CharField(max_length=100)),
                ('Client_Remarks', models.CharField(max_length=200)),
                ('BI_Email_id', models.CharField(max_length=100)),
                ('BI_Laptop', models.CharField(max_length=100)),
                ('BI_Mouse', models.CharField(max_length=100)),
                ('BI_Headphones', models.CharField(max_length=100)),
                ('BI_Computer', models.CharField(max_length=100)),
                ('BI_Remarks', models.CharField(max_length=200, null=True)),
                ('Employee_Status', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.maindashboard')),
            ],
        ),
    ]
