# Generated by Django 4.2 on 2023-08-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindashboard',
            name='is_published',
        ),
    ]
